import type { League } from '../../types'

/** Planteles reales aproximados para generar fixtures mock realistas. */
export const TEAMS: Record<League, string[]> = {
  chile: [
    'Colo-Colo',
    'Universidad de Chile',
    'Universidad Católica',
    'Cobreloa',
    'Coquimbo Unido',
    'Everton',
    'Huachipato',
    "O'Higgins",
    'Palestino',
    'Unión Española',
    'Unión La Calera',
    'Audax Italiano',
    'Deportes Iquique',
    'Ñublense',
    'Deportes Limache',
    'Deportes La Serena',
  ],
  laliga: [
    'Real Madrid',
    'Barcelona',
    'Atlético de Madrid',
    'Athletic Club',
    'Real Sociedad',
    'Real Betis',
    'Villarreal',
    'Valencia',
    'Sevilla',
    'Girona',
    'Osasuna',
    'Rayo Vallecano',
    'Celta de Vigo',
    'Getafe',
    'Mallorca',
    'Espanyol',
    'Alavés',
    'Las Palmas',
  ],
  premier: [
    'Manchester City',
    'Arsenal',
    'Liverpool',
    'Manchester United',
    'Chelsea',
    'Tottenham',
    'Newcastle',
    'Aston Villa',
    'Brighton',
    'West Ham',
    'Everton',
    'Wolves',
    'Fulham',
    'Crystal Palace',
    'Brentford',
    'Nottingham Forest',
    'Bournemouth',
    'Burnley',
  ],
  seriea: [
    'Inter', 'Milan', 'Juventus', 'Napoli', 'Roma', 'Lazio', 'Atalanta',
    'Fiorentina', 'Bologna', 'Torino', 'Udinese', 'Genoa', 'Monza', 'Como',
  ],
  bundesliga: [
    'Bayern München', 'Bayer Leverkusen', 'RB Leipzig', 'Borussia Dortmund',
    'Eintracht Frankfurt', 'VfB Stuttgart', 'Wolfsburg', 'SC Freiburg',
    'Werder Bremen', 'Union Berlin', 'Mainz 05', 'Augsburg', 'Hoffenheim',
    'Borussia M.Gladbach',
  ],
  ligue1: [
    'Paris Saint-Germain', 'Monaco', 'Marseille', 'Lille', 'Lyon', 'Nice',
    'Lens', 'Rennes', 'Strasbourg', 'Brest', 'Nantes', 'Toulouse', 'Reims',
    'Auxerre',
  ],
  primeira: [
    'Benfica', 'Porto', 'Sporting CP', 'Braga', 'Vitória SC', 'Moreirense',
    'Famalicão', 'Gil Vicente', 'Estoril', 'Boavista', 'Rio Ave', 'Casa Pia',
  ],
  eredivisie: [
    'PSV', 'Feyenoord', 'Ajax', 'AZ Alkmaar', 'FC Twente', 'FC Utrecht',
    'NEC Nijmegen', 'Sparta Rotterdam', 'Go Ahead Eagles', 'Heerenveen',
    'FC Groningen', 'PEC Zwolle',
  ],
  brasileirao: [
    'Flamengo', 'Palmeiras', 'Botafogo', 'Fluminense', 'São Paulo',
    'Corinthians', 'Grêmio', 'Internacional', 'Atlético Mineiro', 'Cruzeiro',
    'Fortaleza', 'Bahia', 'Vasco da Gama', 'Athletico Paranaense',
  ],
  argentina: [
    'River Plate', 'Boca Juniors', 'Racing Club', 'Independiente',
    'San Lorenzo', 'Estudiantes', 'Vélez Sarsfield', 'Talleres',
    'Argentinos Juniors', 'Lanús', 'Defensa y Justicia', 'Rosario Central',
    'Newell\'s Old Boys', 'Huracán',
  ],
}
